In [64]:
import os
import shutil
from tqdm import tqdm
from random import shuffle
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from glob import glob

import torch

from sklearn.model_selection import train_test_split

In [136]:
# !cd yolov5 && python val.py --weights ../yolov5/runs/train/exp6/weights/best.pt --data ../yolov5/data/animal.yaml --img 512


In [135]:
!cd yolov5 && python detect.py --weights ../yolov5/runs/train/exp6/weights/best.pt --source ../yolo_data/val/images/



detect: weights=['../yolov5/runs/train/exp6/weights/best.pt'], source=../yolo_data/val/images/, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.0-122-gd885799 torch 1.9.0 CPU

Fusing layers... 
Model Summary: 213 layers, 7047883 parameters, 0 gradients, 15.9 GFLOPs
image 1/560 /Users/neironeiro/Notebooks/kamchatka/yolo_data/val/images/001_1040.jpg: 480x640 1 Тигр, Done. (0.099s)
image 2/560 /Users/neironeiro/Notebooks/kamchatka/yolo_data/val/images/001_1124.jpg: 480x640 1 Тигр, Done. (0.100s)
image 3/560 /Users/neironeiro/Notebooks/kamchatka/yolo_data/val/images/001_1212.jpg: 480x640 1 Тигр, Done. (0.097s)
image 4/560 /Users/neironeiro/Notebooks/kamchatka/yolo_data/val/i

In [132]:
pd.DataFrame(['a', 'a', 'a', 'b']).reset_index().groupby(0).count().sort_values('index').index[-1]

'a'

In [5]:
detection_model = torch.hub.load('ultralytics/yolov5', 'custom', 
                                 path='yolov5/runs/train/exp3/weights/best.pt')

Using cache found in /Users/neironeiro/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2021-12-4 torch 1.9.0 CPU

Fusing layers... 
Model Summary: 213 layers, 7026307 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


In [16]:
image = cv2.cvtColor(cv2.imread('yolo_data/val/images/001_396.jpg'), cv2.COLOR_BGR2RGB)

In [17]:
pred = detection_model(image).pandas().xyxy[0].sort_values('confidence', ascending=False)

In [60]:
plt.imshow(detection_model(image).render()[0])
plt.savefig('image.jpg')

In [59]:
detection_model(image).render()[0]

(1536, 2048, 3)

In [19]:
(pred.xmax.iloc[0] - pred.xmin.iloc[0]) * (pred.ymax.iloc[0] - pred.ymin.iloc[0])

360760.2001476288

In [29]:
image.shape[0] * image.shape[1]

3145728

In [21]:
360760 / 3145728

0.11468251546223958

In [63]:
import torch
import cv2


# @st.cache()
def load_model(path='models/best.pt'):
    detection_model = torch.hub.load('ultralytics/yolov5', 'custom', path=path)
    return detection_model


def detect_image(path, model):
    
    image = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)
    pred = detection_model(image)
    pred_df = pred.pandas().xyxy[0].sort_values('confidence', ascending=False)
    pred_image = pred.render()[0]
    
    if pred_df.shape[0] > 0:
        if pred_df.confidence.iloc[0] > 0.25:
            return pred_image, pred_df.name.iloc[0]
        else:
            return pred_image, 'Неизвестное животное'
    else:
        return image, 'Нет животного'
    
    
detection_model = load_model('yolov5/runs/train/exp3/weights/best.pt')
image, prediction = detect_image('yolo_data/val/images/001_396.jpg', detection_model)

Using cache found in /Users/neironeiro/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2021-12-4 torch 1.9.0 CPU

Fusing layers... 
Model Summary: 213 layers, 7026307 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


# Mapping

In [ ]:
54.804471, 160.351873
54.801694, 160.371785
54.798124, 160.371270
54.795446, 160.353589
54.796240, 160.346551

In [72]:
np.random.choice(a=[-1, 0, 1], size=(100, 2))

array([[ 0,  0],
       [ 1,  1],
       [ 0, -1],
       [ 0,  1],
       [ 0,  1],
       [ 1, -1],
       [ 0,  0],
       [-1,  0],
       [-1,  1],
       [ 1,  0],
       [ 1, -1],
       [ 0,  0],
       [ 1,  0],
       [ 0, -1],
       [-1, -1],
       [ 1, -1],
       [ 1, -1],
       [-1,  1],
       [ 1,  1],
       [ 1,  1],
       [-1, -1],
       [-1,  1],
       [ 1, -1],
       [ 1,  1],
       [-1,  0],
       [-1,  1],
       [ 1,  0],
       [-1, -1],
       [ 1, -1],
       [-1,  0],
       [ 0,  0],
       [ 0, -1],
       [-1,  0],
       [ 0, -1],
       [ 1,  0],
       [ 0,  1],
       [ 0, -1],
       [ 0, -1],
       [ 0,  1],
       [-1,  0],
       [ 1,  1],
       [-1,  0],
       [ 1,  0],
       [ 0, -1],
       [ 0, -1],
       [ 1,  0],
       [ 1, -1],
       [ 0,  0],
       [-1, -1],
       [-1,  0],
       [ 0,  0],
       [-1,  0],
       [-1,  0],
       [ 1, -1],
       [ 0, -1],
       [ 0,  1],
       [-1,  1],
       [ 1,  0],
       [-1,  0

In [73]:
np.zeros((1, dims))

array([[          0,           0]])

In [86]:
path[:10, :]

array([     54.804,      215.16,      215.16, ...,      214.75,      214.75,      214.75])

In [87]:
step_set

[-0.005, 0, 0.005]

In [97]:
# # Simulate steps
# origin = np.array([[54.790784, 160.378652]])
# steps = np.random.choice(a=[-0.005, 0, 0.005], size=(200, 2))
# path = np.concatenate([origin, steps]).cumsum(0)

# df = pd.DataFrame()
# df['latitude'] = path[:, 0]
# df['longitude'] = path[:, 1]
# df.to_excel('df.xlsx')

In [109]:
pd.read_csv('lisa_tracking.csv', sep=';', index_col=0, decimal=',').to_csv('lisa_tracking.csv', index=False)

In [110]:
pd.read_csv('lisa_tracking.csv')

latitude   longitude animal
0    54.790784  160.378652   Лиса
1    54.790784  160.373652   Лиса
2    54.795784  160.378652   Лиса
3    54.795784  160.383652   Лиса
4    54.795784  160.383652   Лиса
..         ...         ...    ...
196  54.795784  160.363652   Лиса
197  54.795784  160.358652   Лиса
198  54.800784  160.363652   Лиса
199  54.805784  160.363652   Лиса
200  54.810784  160.358652   Лиса

[201 rows x 3 columns]